version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build --$BUILD_ENV
      # - npm run build --prod
  post_build:
    commands:
        - aws s3 sync dist/ s3://profil-software-front-deploy  --delete
        # - aws s3 sync dist/ s3://heroes-angular  --delete

